name: Release RTSan binaries

on:
  push:
    branches: [ "feature/release-action" ]

jobs:
  linux:
    strategy:
      matrix:
          machine: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.machine }}
    name: Ubuntu 24.04
    steps:
    - name: Download sources
      uses: llvm/actions/get-llvm-project-src@main
      with:
        repo: "llvm/llvm-project"
        ref: "llvmorg-20.1.0"
    - name: Build and Test
      uses: llvm/actions/build-test-llvm-project@main
      with:
        cmake_args: "-G Ninja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_PROJECTS=\"clang;compiler-rt\" -DLLVM_TARGETS_TO_BUILD=Native"
        build_target: "rtsan"
    - name: Find binary
      run: find /home/runner/work/RTSanStandaloneSwift/RTSanStandaloneSwift/ -name "libclang_rt.rtsan.a"
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: "libclang_rt.rtsan.a"
        path: "/home/runner/work/RTSanStandaloneSwift/RTSanStandaloneSwift/build/lib/clang/20/lib/**/libclang_rt.rtsan.a"

